title: iNUX Question Pools
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gw-inux.github.io/iNUX-Question-Pools

aux_links:
  Template Repository: https://github.com/gw-inux/iNUX-Question-Pools
